BEGIN;
CREATE EXTENSION device_type;
SELECT 'phone'::device_type > 'ipod'::device_type;
SELECT 'phone'::device_type >= 'ipod'::device_type;
SELECT 'ipod'::device_type < 'pc'::device_type;
SELECT NOT('phone'::device_type < 'ipod'::device_type);
SELECT NOT('phone'::device_type <= 'ipod'::device_type);
ROLLBACK;
BEGIN;
CREATE EXTENSION device_type;
SELECT 'phone'::device_type > 'ipod'::device_type;
SELECT 'phone'::device_type >= 'ipod'::device_type;
SELECT NOT('phone'::device_type < 'ipod'::device_type);
SELECT NOT('phone'::device_type <= 'ipod'::device_type);
ROLLBACK;
BEGIN;
CREATE EXTENSION device_type;
SELECT NOT('phone'::device_type = 'ipod'::device_type);
SELECT 'ipod'::device_type = 'ipod'::device_type;
ROLLBACK;
BEGIN;
CREATE EXTENSION device_type;
SELECT 'phone'::device_type != 'ipod'::device_type;
SELECT NOT('ipod'::device_type != 'ipod'::device_type);
ROLLBACK;
