BEGIN;
-- device_type_op should implement gt;
-- ./spec/os_name_op_spec.rb:8;
CREATE EXTENSION device_type;
SELECT 'phone'::device_type > 'ipod'::device_type;
SELECT 'phone'::device_type >= 'ipod'::device_type;
SELECT 'ipod'::device_type < 'pc'::device_type;
SELECT NOT('phone'::device_type < 'ipod'::device_type);
SELECT NOT('phone'::device_type <= 'ipod'::device_type);
ROLLBACK;
BEGIN;
-- device_type_op should implement lt;
-- ./spec/os_name_op_spec.rb:16;
CREATE EXTENSION device_type;
SELECT 'phone'::device_type > 'ipod'::device_type;
SELECT 'phone'::device_type >= 'ipod'::device_type;
SELECT NOT('phone'::device_type < 'ipod'::device_type);
SELECT NOT('phone'::device_type <= 'ipod'::device_type);
ROLLBACK;
BEGIN;
-- device_type_op should implement eq;
-- ./spec/os_name_op_spec.rb:23;
CREATE EXTENSION device_type;
SELECT NOT('phone'::device_type = 'ipod'::device_type);
SELECT 'ipod'::device_type = 'ipod'::device_type;
ROLLBACK;
BEGIN;
-- device_type_op should implement neq;
-- ./spec/os_name_op_spec.rb:28;
CREATE EXTENSION device_type;
SELECT 'phone'::device_type != 'ipod'::device_type;
SELECT NOT('ipod'::device_type != 'ipod'::device_type);
ROLLBACK;
