BEGIN;
-- device_type should pass valid device_type;
-- ./spec/os_name_spec.rb:8;
CREATE EXTENSION device_type;
SELECT 'bot'::device_type;
SELECT 'console'::device_type;
SELECT 'ipod'::device_type;
SELECT 'mac'::device_type;
SELECT 'pc'::device_type;
SELECT 'phone'::device_type;
SELECT 'server'::device_type;
SELECT 'simulator'::device_type;
SELECT 'tablet'::device_type;
SELECT 'tv'::device_type;
SELECT 'unknown'::device_type;
ROLLBACK;
BEGIN;
-- device_type should rais an exception on invalid device_type;
-- ./spec/os_name_spec.rb:26;
CREATE EXTENSION device_type;
SELECT 'kermit'::device_type;
ROLLBACK;
BEGIN;
-- device_type should rais an exception on invalid device_type;
-- ./spec/os_name_spec.rb:30;
CREATE EXTENSION device_type;
SELECT 'tb'::device_type;
ROLLBACK;
